ebdjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,news_view
from .forms import EmailValidationOnForgotPassword, MyAuthenticationForm, MySetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('noticias/', news_view, name='news'),    
    path('municipios/', include('municipios.urls', namespace='municipios')),
    path('punto_referencia/', include('punto_referencia.urls', namespace='punto_referencia')),
    path('perfiles/', include('perfiles.urls', namespace='perfiles')),    
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html',authentication_form=MyAuthenticationForm ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),        
    path('password-reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword,template_name="auth/password_reset.html"), name='password_reset'),            
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"), name='password_reset_done'),            
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auth/password_reset_confirm.html", form_class=MySetPasswordForm), name='password_reset_confirm'),            
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"), name='password_reset_complete'),            
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfiles/urls.py
from django.urls import path
from .views import my_profile_view,create_user_view,delete_user_view,user_list_view,show_user_view,MyPasswordChangeView,MyPasswordChangeDoneView,descargar_manual_view
from .forms import MyChangePasswordForm

app_name = 'perfiles'

urlpatterns = [
    path('mi_perfil/', my_profile_view, name='mi-perfil'),
    path('create_user/', create_user_view, name='create-user'),
    path('list_users/', user_list_view, name='list-user'),
    path('delete_user/<user_id>/', delete_user_view, name='delete-user'),
    path('show_user/<user_id>/',  show_user_view, name='show-user'),
    path('change_password/', MyPasswordChangeView.as_view(form_class=MyChangePasswordForm), name='password-change'),
    path('change_password/done/', MyPasswordChangeDoneView.as_view(), name='password-change-done'),
    path('manual_usuario/', descargar_manual_view, name='ver-manual'),
]

perfiles/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    bio = models.TextField(default="no bio...")
    foto = models.ImageField(upload_to='fotos/', default='no_picture.jpg')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Perfil de {self.user.username}"
    
class ManualUsuario(models.Model):
    file_name = models.CharField(max_length=120)
    pdf_file = models.FileField(upload_to='manuales')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.file_name)

perfiles/forms.py
from django import forms
from .models import Perfil
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.forms import  TextInput, EmailInput, FileInput

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['foto']

        widgets = {
            'foto':FileInput(attrs={
                'class': 'form-control'
            })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['foto'].widget.clear_checkbox_label = 'Limpiar'
        self.fields['foto'].widget.initial_text = "Actual"
        self.fields['foto'].widget.input_text = "Cambiar a"        

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']
        labels = {
            'username': _('Nombre de Usuario'),
            'email': _('Correo'),
            'first_name': _('Nombres'),
            'last_name': _('Apellidos'),
        }
        help_texts = {
            'username': _('Requerido. 150 caracteres o menos. Letras, Dígitos y @/./+/-/_ solamente.'),
        }
        widgets = {
            'username': TextInput(attrs={
                'class': "form-control", 
                'style': 'font-family: "Roboto", sans-serif;background: #0be11b26;width: 100%;border: 0;margin: 0 0 15px;padding: 15px;box-sizing: border-box;font-size: 14px; ',
                'placeholder': 'Nombre de Usuario'
                }),
            'email': EmailInput(attrs={
                'class': "form-control", 
                'style': 'font-family: "Roboto", sans-serif;outline: 0;background: #0be11b26;width: 100%;border: 0;margin: 0 0 15px;padding: 15px;box-sizing: border-box;font-size: 14px; ',
                'placeholder': 'Correo'
                }),
            'first_name': TextInput(attrs={
                'class': "form-control", 
                'style': 'font-family: "Roboto", sans-serif;outline: 0;background: #0be11b26;width: 100%;border: 0;margin: 0 0 15px;padding: 15px;box-sizing: border-box;font-size: 14px; ',
                'placeholder': 'Nombre(s)'
                }),
            'last_name': TextInput(attrs={
                'class': "form-control", 
                'style': 'font-family: "Roboto", sans-serif;outline: 0;background: #0be11b26;width: 100%;border: 0;margin: 0 0 15px;padding: 15px;box-sizing: border-box;font-size: 14px; ',
                'placeholder': 'Apellido(s)'
                }),
        }

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Correo")
    first_name = forms.CharField(max_length=30, label="Nombre")
    last_name = forms.CharField(max_length=30, label="Apellido")
    is_staff = forms.BooleanField(required=False, label="¿Es Admininstrador?")

    error_messages = {
        'password_mismatch': "Las contraseñas no coinciden.",
    }

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Contraseña'
        self.fields['password2'].label = 'Confirmar Contraseña'

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2','is_staff')
        labels = {'username': _('Nombre de Usuario'),
                    }
        help_texts = {
            'username': _('Requerido. 150 caracteres o menos. Letras, Dígitos y @/./+/-/_ solamente.'),
            'password1': {

            },
            'password2': _('Ingrese la contraseña anterior, para verificar.'),
        }
        error_messages = {
            'username': {
                'unique': 'Ya existe un usuario con ese nombre.',
            },
        }

    def save(self, commit=True):
        user = super(MyUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.is_staff = self.cleaned_data['is_staff']
            user.save()
        return user

class MyChangePasswordForm(PasswordChangeForm):
    error_messages = {
        **SetPasswordForm.error_messages,
        "password_incorrect": _(
            "Su contraseña anterior es incorrecta, por favor, digitela nuevamente."
        ),
    }

    def __init__(self, *args, **kwargs):
        super(MyChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = 'Contraseña Actual'
        self.fields['new_password1'].label = 'Contraseña Nueva'
        self.fields['new_password2'].label = 'Confirmar Contraseña'

perfiles/views.py
from django.shortcuts import render
from .models import ManualUsuario, Perfil
from .forms import ProfileUpdateForm,MyUserCreationForm, UserUpdateForm
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.decorators import login_required
from django.conf import settings
import boto3
from django.http import HttpResponseRedirect

@login_required
def my_profile_view(request):
    perfil = Perfil.objects.get(user=request.user)
    confirm = False
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=perfil)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            confirm = True           
            
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(request.POST or None, request.FILES or None, instance=perfil)
    
    context = {
        'perfil':perfil,
        'u_form':u_form,
        'p_form':p_form,
        'confirm':confirm,
    }
    return render(request, 'perfiles/my_profile.html', context)

class MyPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('perfiles:password-change-done')
    template_name = 'perfiles/password_change.html'   

class MyPasswordChangeDoneView(PasswordChangeDoneView):
    template_name= 'perfiles/password_change_done.html'    

@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('home'))
def show_user_view(request,user_id):
    user = User.objects.get(pk=user_id)
    context = {        
            'user':user,
        }
    return render(request, 'perfiles/show_user.html', context)

@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('home'))
def user_list_view(request):
    user_list = User.objects.all().exclude(is_superuser=True)
    context = {        
        'user_list':user_list,
    }
    return render(request, 'perfiles/list_users.html', context)

@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('home'))
def create_user_view(request):
    users = User.objects.all()
    form = MyUserCreationForm(request.POST or None)    
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('perfiles:list-user')
            
    context={
        'form':form,
        'users':users,
    }
    return render(request, 'perfiles/create_user.html', context)

@login_required
def delete_user_view(request,user_id):
    user = User.objects.get(pk=user_id)
    user.delete()
    return redirect('perfiles:list-user')

@login_required
def descargar_manual_view(request):
    file = ManualUsuario.objects.order_by('-created').first().pdf_file
    s3 = boto3.client('s3',
                        aws_access_key_id = settings.AWS_ACCESS_KEY_ID,
                        aws_secret_access_key = settings.AWS_SECRET_ACCESS_KEY
                        )
    url = s3.generate_presigned_url('get_object', 
                                    Params = { 
                                                'Bucket': settings.AWS_STORAGE_BUCKET_NAME, 
                                                'Key': str(file), }, 
                                    ExpiresIn = 600,)
    return HttpResponseRedirect(url)
    

    

perfiles/templates/perfiles/create_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Crear Usuario{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}

{% block content %}
<a href="{% url 'perfiles:list-user' %}" class="btn btn-dark mt-3"> <i class="fa fa-arrow-left me-2"></i>Volver</a>
<h1 class="headers m-2">Registrar Usuario</h1>
<form action="" method="POST" class="">
    <div class="form-row">    
      {% csrf_token %}
      {{form|crispy}}
    </div>
<button type="submit" class="btn btn-success mt-3 mb-3">Crear Usuario</button>
</form>
{% endblock content %}

perfiles/templates/perfiles/list_users.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Usuarios
{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}
{% block content %}
<br/>
  <div class="row m-5 justify-content-center">
    <div class="col-6">
      <h1 class="headers">Gestión de Usuarios</h1>
    </div>
    <div class="col-6" align="center">
      <a class="btn btn-lg btn-success" href="{% url 'perfiles:create-user' %}" role="button">Registrar Usuarios</a>
    </div>        
  </div>    
  <table class="table table-hover ">        
    <tbody>
    {% for usuario in user_list %}
      <tr>
        <td>    
          <div class="row"       >
            <div class="col">
              <a class="link" href="{% url 'perfiles:show-user' usuario.id %}">{{usuario}}</a>                              
            </div>
            <div class="col p-2">
              <a class="btn btn-outline-danger ms-5" href="{% url 'perfiles:delete-user' usuario.id %}">Eliminar</a>
            </div>
          </diV>            
        </td>
      </tr>
    {% endfor %}       
    </tbody>
  </table>

    
{% endblock content %}

perfiles/templates/perfiles/my_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Mi Perfil{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}
{% block content %}

{% if confirm %}
    <div class="alert alert-primary" role="alert">
        Tu perfil ha sido actualizado
    </div>
{% endif %}
  <div class="row">
    <h1 class="headers m-3">Mi Perfil</h1>

    <div class="col-md-4 border-right align-self-center ">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <img  alt="mi-perfil" class="rounded-circle account-img" src="{{ user.perfil.foto.url }}">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
        <a class="btn btn-success " href="{% url 'perfiles:password-change'%}">Cambiar Contraseña</a>
      </div>      
    </div>  
    
    <div class="col-md-8">
      <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
      <div class="p-3 py-5">
        <div class="row mt-2">
          <div class="col-md-6">
            <div class="form-group">
              <label>Nombre de Usuario</label>
              {{u_form.username}}
            </div>            
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label>Correo</label>
              {{u_form.email}}
            </div>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col-md-6">
            <div class="form-group">
              <label>Nombre(s)</label>
              {{u_form.first_name}}
            </div>            
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label>Apellido(s)</label>
              {{u_form.last_name}}
            </div>
          </div>
        </div>
        <div class="row mt-2">
            <div class="form-group">
              <label>Foto</label>
              {{p_form.foto}}
            </div>            
          </div>
        </div>
        <button type="submit" class="btn btn-success mt-3 mb-3">Actualizar</button>  
      </div>
      
      </form>
    </div>
    
</div>


  
  


{% comment %} <div class="p-3 border border-2 ">  
    <div class="d-flex">
      <img  alt="mi-perfil" class="rounded-circle account-img" src="{{ user.perfil.foto.url }}">
      <div class="media-body align-self-center">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-5">
      <a class="btn btn-success " href="{% url 'perfiles:password-change'%}">Cambiar Contraseña</a>
    </div>
    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom my-5 headers">Info perfil</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Actualizar</button>
        </div>
    </form>
</div> {% endcomment %}

{% endblock content %}

perfiles/templates/perfiles/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Cambiar Contraseña{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}

{% block content %}

<h1 class="headers mt-5">Cambiar Contraseña</h1>
<a href="{% url 'perfiles:mi-perfil' %}" class="btn btn-dark mt-3"> <i class="fa fa-arrow-left me-2"></i>Volver</a>
<div class="bloque">
<form action="" method="POST" id="dataForm">
    <div class="form-row">    
      {% csrf_token %}
      {{form|crispy}}
    </div>
<button type="submit" class="btn btn-success mt-3 mb-3">Actualizar Contraseña</button>
</form>
</div>

{% endblock content %}

perfiles/templates/perfiles/password_change_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Cambiar Contraseña{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}

{% block content %}
<div class="exito">
<div class="card">
  <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
    <i class="fa fa-check-circle  " aria-hidden="true"></i>
  </div>
  <h1>¡Su contraseña ha cambiado satisfactoriamente!</h1>  
  </div>
</div>
{% endblock content %}

perfiles/templates/perfiles/show_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Usuarios
{% endblock title %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'perfiles/style.css' %}">
{% endblock styles %}

{% block content %}
<a href="{% url 'perfiles:list-user' %}" class="btn btn-dark mt-3"> <i class="fa fa-arrow-left me-2"></i>Volver</a>
<div class="mt-100">
    <div class="row m-5">
        <center>
        <h1 class="headers">Usuario {{user}}</h1>
        <ul class="list-group">
            <li class="list-group-item"><strong>Correo: </strong>{{user.email}}</li>
            <li class="list-group-item"><strong>¿Es Administrador?: </strong>{% if user.is_staff %}Si{% else %}No{% endif %}</li>
            <li class="list-group-item"><strong>Nombres: </strong>  {{user.first_name}} </li>
            <li class="list-group-item"><strong>Apellidos: </strong>{{user.last_name}}</li>
            <li class="list-group-item"><strong>Fecha de Registro: </strong>{{user.date_joined}}</li>
        </ul>
        </center>   
</div>
</div>  

{% endblock content %}