ebdjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,news_view
from .forms import EmailValidationOnForgotPassword, MyAuthenticationForm, MySetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('noticias/', news_view, name='news'),    
    path('municipios/', include('municipios.urls', namespace='municipios')),
    path('punto_referencia/', include('punto_referencia.urls', namespace='punto_referencia')),
    path('perfiles/', include('perfiles.urls', namespace='perfiles')),    
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html',authentication_form=MyAuthenticationForm ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),        
    path('password-reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword,template_name="auth/password_reset.html"), name='password_reset'),            
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"), name='password_reset_done'),            
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auth/password_reset_confirm.html", form_class=MySetPasswordForm), name='password_reset_confirm'),            
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"), name='password_reset_complete'),            
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

punto_referencia/urls.py
from django.urls import path
from .views import (
    reports_view, 
    chartView,
    csv_upload_view,
    mapView,
    uploadTemplateView,
    load_punto_referencia,
    export
    )

app_name = 'punto_referencia'

urlpatterns = [
    path('reports/', reports_view, name='reports'),
    path('charts/', chartView, name='charts'),
    path('clima/', uploadTemplateView, name='clima'),
    path('upload/', csv_upload_view, name='upload'),
    path('map/', mapView, name='map'),
    path('export/', export, name='export'),
    path('ajax/load-cities/', load_punto_referencia, name='ajax_load_cities'),  # <-- this one here
   
]

punto_referencia/models.py
from django.db import models
from municipios.models import Municipio

class Punto_Referencia(models.Model):
    name = models.CharField(max_length=120)
    longitud = models.FloatField()
    latitud = models.FloatField()
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Dato(models.Model):
    year = models.DateField()
    irradiance = models.FloatField(help_text='MJ/m^2/day')
    temperature = models.FloatField(help_text='°C')
    relative_humidity = models.FloatField(help_text='%')
    precipitation = models.FloatField(help_text='mm/day')
    punto_referencia = models.ForeignKey(Punto_Referencia, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.punto_referencia.name}: {self.year}"

class CSV(models.Model):
    file_name = models.CharField(max_length=120)
    csv_file = models.FileField(upload_to='csvs')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.file_name)
    

punto_referencia/forms.py
from django import forms
from municipios.models import Municipio
from punto_referencia.models import Dato, Punto_Referencia

VARIABLES = (    
    ('temperature', ("Temperatura")),
    ('relative_humidity', ("Humedad Relativa")),
    ('irradiance', ("Irradiación")),
    ('precipitation', ("Precipitación"))    
)

class TerritoriesSearchForm(forms.Form):
    date_from = forms.DateField(label=("Fecha Desde"),widget=forms.DateInput(attrs={'type':'date'}))
    date_to = forms.DateField(label=("Fecha Hasta"),widget=forms.DateInput(attrs={'type':'date'}))    
    punto_referencia = forms.ModelChoiceField(queryset=Punto_Referencia.objects.all())

class MunicipiosSearchForm(forms.Form):
    municipio = forms.ModelChoiceField(queryset=Municipio.objects.all())

class ChartForm(forms.Form):
    date_from = forms.DateField(label=("Fecha Desde"), widget=forms.DateInput(attrs={'type':'date'}))
    date_to = forms.DateField(label=("Fecha Hasta"),widget=forms.DateInput(attrs={'type':'date'}))    
    variable = forms.ChoiceField(widget=forms.Select(), required=True, choices=VARIABLES)
    
class Punto_ReferenciaForm(forms.ModelForm):
    class Meta:
        model = Punto_Referencia
        fields = ('municipio',)

class DatoForm(forms.ModelForm):
    class Meta:
        model = Dato
        fields = ('punto_referencia',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['punto_referencia'].queryset = Punto_Referencia.objects.none()

 
       
            

punto_referencia/views.py
from django import template
from django.http import HttpResponse
from django.shortcuts import render
import numpy as np
from .forms import ChartForm, DatoForm, MunicipiosSearchForm, TerritoriesSearchForm, Punto_ReferenciaForm
from .models import Dato, CSV
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from punto_referencia.models import Punto_Referencia
from municipios.models import Municipio
from django.http import JsonResponse
from django.http import HttpResponse
import pandas as pd
from django.contrib.auth.decorators import login_required
import folium
from branca.element import Figure
from django.core.paginator import Paginator
from datetime import datetime
import csv
import boto3
from django.conf import settings

register = template.Library()
@register.filter
def get_attr(object, name):
    return getattr(object, name, '')

"""
Vista para reportes del clima
"""
@login_required
def reports_view(request):
    form = TerritoriesSearchForm(request.POST or None)
    no_data = obj = datos=punto_referencia=date_from=date_to=date_max=date_min= None
    objs = []
                
    if request.method == 'POST':
        if form.is_valid():
            date_from = request.POST.get('date_from')
            date_to = request.POST.get('date_to')        
            id_punto_referencia = request.POST.get('punto_referencia')
            punto_referencia = Punto_Referencia.objects.get(id=id_punto_referencia)                 
            objs = Dato.objects.filter(
                    punto_referencia=punto_referencia,
                    year__lte=date_to,
                    year__gte = date_from                
                    )
            date_max=objs.last().year.strftime("%Y")
            date_min=objs.first().year.strftime("%Y")
            obj = objs[:10]    
            #Se usan cookies para guardar el punto de referencia y el rango de tiempo para usarlos en la vista de exportar.            
            request.session['punto_referencia'] = id_punto_referencia
            request.session['date_to'] = date_to
            request.session['date_from'] = date_from
            if len(obj) == 0:
                no_data = 'No se encontraron registros en las fechas seleccionadas.'
        #Mostrar los 10 primeros registros encontrados
        p = Paginator(obj,10)        
        page = request.GET.get('page')
        datos = p.get_page(page)

    context = {
        'form': form,
        'obj': obj,  
        'cantidad':len(objs),
        'date_from':date_min,
        'date_to':date_max,
        'punto_referencia':punto_referencia, 
        'datos': datos,
        'no_data': no_data,
    }
    return render(request,'punto_referencia/reports.html', context)

""" 
Función para exportar los datos consultados del clima en la vista de reportes como CSV.
"""
def export(request):
    #Se obtienen el punto de referencia y el rango de tiempo guardadas en la sesión
    id_punto_referencia=request.session['punto_referencia'] 
    punto_referencia = Punto_Referencia.objects.get(id=id_punto_referencia)                        
    date_to=request.session['date_to'] 
    date_from=request.session['date_from'] 
    obj = Dato.objects.filter(
                    punto_referencia=punto_referencia,
                    year__lte=date_to,
                    year__gte = date_from                
                    )    
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow(['Fecha','Radiacion Solar', 'Temperatura','Humedad Relativa','Precipitacion'])
    for dato in obj.values_list('year','irradiance','temperature','relative_humidity', 'precipitation'):
        writer.writerow(dato)

    response['Content-Disposition']='attachment;filename=Reporte '+punto_referencia.name+' ('+date_from+' - '+date_to+') '+'.csv'

    return response

"""
Vista del mapa con los puntos de referencia y los municipios a los que hacen parte
"""
def mapView(request):
    #Son 19 colores disponibles por folium para el color de icono.
    colors = ['red', 'orange', 'green', 'darkblue', 'darkgreen', 'black', 'darkred', 'cadetblue', 'pink', 'lightblue', 'purple', 'beige', 'gray', 'lightgray', 'blue', 'darkpurple', 'lightred', 'lightgreen', 'white']
    #Coordenadas para centrar el mapa en cesar
    lon = 9.129754392830863
    lat = -73.53600433475354
    punto_referencia = Punto_Referencia.objects.all()   
    municipios = Municipio.objects.all()
    municipiosPk = [] # Lista de las PK de los municipios
    municipiosName= [] # Lista de los nombres de los municipios
    for municipio in municipios:
        municipiosPk.append(municipio.pk)
        municipiosName.append(municipio.name)    
    municipiosColorName = {}
    municipiosColor = {} # Diccionario con los colores de cada municipio. 
                        #La PK del Municipio es la key y el value es un color de la lista de colores 'colors'
    for i in range(len(municipiosPk)):
        municipiosColorName[municipiosName[i]] = colors[i]
        municipiosColor[municipiosPk[i]] = colors[i]   # Ej: diccionario<key=municipioPk, value=color
                                                      #  {'1':'red; '2':orange'  ....}
    fig = Figure(width="100%", height="550px")
    m = folium.Map(
        location=[lon,lat],
        tiles="OpenStreetMap",        
        width="100",
        height="100",
        zoom_start=8)    
    
    # Capas de visualización (OpenStreetMap, Relieve y Satelital)
    folium.TileLayer(name="Relieve",
    tiles='https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', 
    attr='Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)').add_to(m)        
    folium.TileLayer(name="Satelital",
    tiles='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', 
    attr='Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community').add_to(m)    
    folium.LayerControl().add_to(m)
    fig.add_child(m)
    folium.LatLngPopup().add_to(m)

    #Ubicación de cada punto de referencia a partir de su geoubicación y un color de marcador según el municipio al que pertenece 
    for item in punto_referencia:
        folium.CircleMarker(location=(item.longitud,item.latitud),radius=10, fill_color='green').add_to(m)
        folium.Marker(
            location=(item.longitud,item.latitud),popup=item.name,tooltip=item.name, 
            icon=folium.Icon(color=municipiosColor[item.municipio.pk], icon_color='#ffffff')).add_to(m)
        folium.map.Layer()

    m = m._repr_html_()
    context={
        'map':m,
        'municipios': municipiosColorName, 
    }
    return render(request,'punto_referencia/mapa.html',context)

""" 
Vista para los gráficos de las variables del clima
"""
@login_required
def chartView(request):
    unidadesDict = {'temperature': '°C', 'relative_humidity': "%", 'irradiance': "MJ/m^2", 'precipitation': "mm"}
    punto_referenciaForm = Punto_ReferenciaForm()
    datoForm = DatoForm(request.POST or None)
    form = ChartForm(request.POST or None)
    date_from = request.POST.get('date_from')
    date_to = request.POST.get('date_to')   
    date_max=date_min=qs = variable = punto_referencia = punto_referenciaObj = unidades=df=dati=datos=fechas=variableName=yDataPrec=yDatosPrec=None    
    periodoLargo=False
    data = []
    fechas=[]
    yDatosFechas=[]
    promedio = minimo = maximo = 0  
    
    if request.method == 'POST':
        if form.is_valid():
            desde = request.POST.get('date_from')
            desde = datetime.strptime(desde,'%Y-%m-%d').strftime("%d/%m/%Y")
            hasta = request.POST.get('date_to')
            hasta = datetime.strptime(hasta,'%Y-%m-%d').strftime("%d/%m/%Y")
            punto_referencia = request.POST.get('punto_referencia')
            variable = str(request.POST.get('variable'))
            variableName = form.cleaned_data['variable']
            variableName = dict(form.fields['variable'].choices)[variableName]            
            punto_referenciaObj = Punto_Referencia.objects.get(id=punto_referencia)                 
            #Conjunto de datos del punto de referencia seleccionado
            qs = Dato.objects.filter(
                punto_referencia = punto_referencia,
                year__lte=date_to,
                year__gte = date_from  
            )
            #Se obtiene la fecha mínima y la fecha máxima en que se encontraron los datos
            date_min=qs.first().year.strftime("%d/%m/%Y")
            date_max=qs.last().year.strftime("%d/%m/%Y")
            #El periodo de tiempo es 'largo' si el periodo es mayor a 5 años
            periodoLargo = True if len(qs)>1825 else False #Periodo largo son periodos mayores a 5 años            
            df = pd.DataFrame(list(qs.values('year', variable)))
            #Para precipitación se suma el total de precipitación que hubo en un periodo de tiempo establecido
            if variableName == "Precipitación":
                # 'dati' agrupa los datos en periodos mensuales
                dati=df.groupby(pd.PeriodIndex(df['year'], freq="M"))[variable].sum().reset_index()
                datos = [i for i in dati[variable].values]
                minimo = min(datos)
                maximo = max(datos)
                promedio = np.average(datos)
                #Si se analiza un periodo de tiempo mayor a un año, se agrega la gráfica de precipitación anual
                if len(qs)>365:
                    yDataPrec = df.groupby(pd.PeriodIndex(df['year'], freq="Y"))[variable].sum().reset_index()
                    yDatosPrec = [i for i in yDataPrec[variable].values]

punto_referencia/templates/punto_referencia/from_file.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'punto_referencia/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}Clima{% endblock title %}

{% block content %}
<h1 class="headers">Módulo Clima</h1>
<hr><br>
<br>

<div class="row align-items-center">
    <div class="col-6">
        <div id="alert-box"></div>
        <form action="" method="POST" id="my-form">
            {% csrf_token %}
            {{form|crispy}}    
        </form>
        <br>
        
        <form id="my-dropzone" class="dropzone dz">
            {% csrf_token %}
            <div class="dz-message needsclick">
                <!--begin::Icon-->
                <i class="fa fa-cloud-upload fa-5x" aria-hidden="true"></i>
                <!--end::Icon-->
                <br>
                <br>
                <!--begin::Info-->
                <div class="ms-4">
                    <h3 class="headers">Arrastra o Selecciona el archivo de carga.</h3>
                    <span class="fs-7 fw-semibold text-gray-400">Máximo 1 archivo en CSV.</span>
                </div>
                <div class="fallback">
                    <input name="file" type="file" /> 
                </div>
                <!--end::Info-->
            </div>
        </form>    
    </div>

    <div class="col-6 text-center">
        <h4>Este módulo se encarga de almacenar los datos correspondientes
            al clima tomados de un punto específico.
        </h4><br>
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Al momento de cargar un archivo tener en cuenta:</h4>
            <hr>
            <p>Cargar un único archivo a la vez.</p>          
            <p>Sólo se admiten archivos en formato .csv.</p>
            <p>Seleccionar el municipio al que pertenece su jurisdicción.</p>
            <p>El nombre del archivo debe ser el del punto_referencia,
                y en caso de tener espacios deben estar separados por guión bajo. Ej: El_Totumal</p>    
        </div>
    </div>
</div>



<button id="upload-btn" type="submit" class="btn btn-success m-3">Guardar</button>
<button onClick="window.location.reload();" type="button" class="btn btn-outline-primary mt-3 mb-3">Cargar Otro</button>

<br/>

{% endblock content %}

punto_referencia/templates/punto_referencia/mapa.html
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- favicon --> 
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <!-- Font Awsome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- semantic UI -->
        <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
        <!--Chart js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
        <!-- Dropzone js -->
        {% comment %} <link rel="stylesheet" href="{% static 'dropzone.css' %}">
        <script src="{% static 'dropzone.js' %}" defer></script> {% endcomment %}
        <script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js" defer></script>
        <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
    
        <!-- Custom js & css -->
        <link rel="stylesheet" href="{% static 'style.css' %}">
    
        <title>SIGAGRO | Mapa</title>
      </head>
    
    <body>
    {% include 'navbar.html' %}
    <div class="map">
        <div class="col-sm-10 mapitem">{{map|safe}}</div>
        <div class="col-sm-2 mapitem">
            <div class="labels">
                <h4 class="alert-heading headers" style="text-align: center;">Municipios</h4>
                <hr>
                    {% for key,value in municipios.items %}
                        <p><i class="fa fa-map-marker" style="color:{{value}};"></i>{{key}}
                        </p>                                                
                    {% endfor %}                    
            </div>
        </div>
    </div>    
    
    <footer class="container-fluid text-center">
        <div class="row">
            <div class="col-sm-4">
                <h3>Contáctenos</h3>    
                <hr>
                <h4>Teléfono: 3112813845</h4>
                <h4>Bucaramanga - Colombia</h4>
                <h4>Cra. 27 # 9</h4>
                
            </div>
            <div class="col-sm-5">
                <h3>Redes Sociales</h3>
                <br>
                <a href="#" id="fa" class="fa fa-facebook"></a>
                <a href="#" id="fa" class="fa fa-twitter"></a>
                <a href="#" id="fa" class="fa fa-linkedin"></a>
                <a href="#" id="fa" class="fa fa-youtube"></a>
            </div>
            <div class="col-sm-3">
                <img src="{% static 'logo.png' %}" class="img-fluid" style="border-radius: 55%; height: 190px;">
            </div>
        </div>
    </footer>
    </body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</html> 


    

punto_referencia/templates/punto_referencia/pdf.html
<html>
    <head>
        <meta charset = 'utf-8'>
        <title>PDF</title>
    </head>
    <body>
        {{myvar}}
    </body>
</html>

punto_referencia/templates/punto_referencia/prueba.html
<option value="">---------</option>
{% for punto_referencia in punto_referencia %}
    <option value="{{ punto_referencia.pk }}">{{ punto_referencia.name }}</option>
{% endfor %}

punto_referencia/templates/punto_referencia/reports.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% url 'punto_referencia:export' as export %}


{% block title %}Reportes Clima{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'municipios/style.css' %}">
{% endblock styles %}
{% block content %}
<br>

<h1 class="headers" style="text-align:center;">Reportes Clima</h1>
<hr/>
<div class="bloque">    
    <form action="" id="dataForm" class="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary mt-3">Consultar</button>
    </form>
</div>
    <br>        
    {% if obj %}
        <h3 class="headers">Boletín informativo del punto de referencia {{punto_referencia.name}} perteneciente al municipio 
            {{punto_referencia.municipio.name}}  </h3>
            <h4 class="headers">Datos históricos entre {{date_from}} y {{date_to}}</h4>
        <hr/>
            <a href={% url 'punto_referencia:export' %} class="btn btn-success mt-3 mb-3">Exportar como CSV</a>            
            <table class="text-center table table-hover table-striped table-bordered mt-3">
                <thead>
                <tr >
                    <th scope="col">Fecha</th>
                    <th scope="col">Radiación Solar</th>
                    <th scope="col">Temperatura</th>
                    <th scope="col">Precipitación</th>
                    <th scope="col">Humedad Relativa</th>
                    <th scope="col">Punto de Referencia</th>
                    <th scope="col">Municipio</th>
                </tr>
                </thead>
                <tbody> 
                    {% for o in obj %}                
                        <tr>
                            <th scope="row">{{o.year}}</th>
                            <td class="table-warning">{{o.irradiance}}</td>
                            <td class="table-success">{{o.temperature}}</td>
                            <td class="table-primary">{{o.precipitation}}</td>
                            <td class="table-info">{{o.relative_humidity}}</td>
                            <td class="table-light">{{o.punto_referencia.name}}</td>
                            <td class="">{{o.punto_referencia.municipio.name}}</td>
                        </tr>   
                    {% endfor %}            
                </tbody>
            </table>
            <p>10 primeros resultados de {{cantidad}}</p>
            <br/>
            <hr/>
    {% endif %}        
    {% if no_data %}
        <div class="alert alert-danger" role="alert">
            {{no_data}}
        </div>      
    {% endif %}

{% endblock content %}

punto_referencia/templates/punto_referencia/statistics.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Estadísticas{% endblock title %}

{% block scripts %}
<script>
    $(document).ready(function(){
                
        if ($("#id_punto_referencia").val() != '') {
            $("#submitButton").prop("disabled",false);
        }else{
            $("#submitButton").prop("disabled",true);
        }

        $("#id_municipio").change(function () {
            if ($(this).val() == '') {
                $("#submitButton").prop("disabled",true);
            }
            if ($("#id_punto_referencia").val() == '') {
                $("#submitButton").prop("disabled",true);
            }
            var url = $("#dataForm").attr("data-cities-url");  // get the url of the `load_cities` view
            var municipioId = $(this).val();  // get the selected country ID from the HTML input
            $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                    data: {
                    'municipio': municipioId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#submitButton").prop("disabled",true);
                        $("#id_punto_referencia").html(data);  // replace the contents of the city input with the data that came from the server
                    }
                });
            });
            $("#id_punto_referencia").change(function () {                
                if ($(this).val() != '') {
                    $("#submitButton").prop("disabled",false);
                }else{
                    $("#submitButton").prop("disabled",true);
                }
            });


        });

</script>

<script>
    $(document).ready(function(){
        const xValues = {{dataX | safe}};
        const yValues = {{dataY | safe}};

        var chartData = {
            datasets: [{
              label: '{{variableX}} vs {{variableY}}' ,
              data: [],
              backgroundColor: 'rgba(223,74,74, 0.4)',
            }]
          }
          for (var i = 0; i < xValues.length; i++) {
            chartData.datasets[0].data.push(
              {
                x: xValues[i], 
                y: yValues[i]
              }
            )
          }
          var chartOptions = {            
            responsive: true
          }

        const ctx = document.getElementById('myChart').getContext('2d');        
        document.getElementById('myChart').width = 200;   

        const myChart = new Chart(ctx, {
            type: 'scatter',
            data: chartData,
            options: chartOptions
        }); 
     
    });
</script>
{% endblock scripts %}

{% block content %}
<h1 class="headers">Estadísticas</h1>
<hr/>
<br/>
<form method="POST" id="dataForm" data-cities-url="{% url 'punto_referencia:ajax_load_cities' %}" >
    {% csrf_token %}    
    {{punto_referenciaForm|crispy}}
    {{datoForm|crispy}}
    {{form |crispy}}
    <button id="submitButton" type="submit" class="btn btn-primary mt-3">Search</button>
</form>

{% if qs %}
<canvas id="myChart" width="100" height="100"></canvas>
{% endif %}

{% endblock content %}