ebdjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,news_view
from .forms import EmailValidationOnForgotPassword, MyAuthenticationForm, MySetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('noticias/', news_view, name='news'),    
    path('municipios/', include('municipios.urls', namespace='municipios')),
    path('punto_referencia/', include('punto_referencia.urls', namespace='punto_referencia')),
    path('perfiles/', include('perfiles.urls', namespace='perfiles')),    
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html',authentication_form=MyAuthenticationForm ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),        
    path('password-reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword,template_name="auth/password_reset.html"), name='password_reset'),            
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"), name='password_reset_done'),            
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auth/password_reset_confirm.html", form_class=MySetPasswordForm), name='password_reset_confirm'),            
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"), name='password_reset_complete'),            
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

municipios/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from .views import create_municipio_view,csv_upload_view,export,reports_view,chartView,AgroClimateView

app_name = 'municipios'

urlpatterns = [
 path('maiz/', create_municipio_view, name = "maiz"),   
 path('upload/', csv_upload_view, name='upload'),
 path('charts/', chartView, name='charts'),
 path('charts/agroclima/', AgroClimateView, name='agroclimate'),
 path('reports/', reports_view, name='reports'),
 path('export/', export, name='export'),

]

municipios/models.py
from django.db import models
from django.forms import DateField

class Municipio(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return str(self.name)

class Dato(models.Model):
    year = models.DateField()
    period = models.CharField(max_length=120)
    area_sembrada=models.FloatField(help_text='Ha')
    area_cosechada=models.FloatField(help_text='Ha')
    produccion=models.FloatField(help_text='T')
    rendimiento=models.FloatField(help_text='T/Ha')
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.municipio.name}: {self.year}"

class CSV(models.Model):
    file_name = models.CharField(max_length=120)
    csv_file = models.FileField(upload_to='csvs')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.file_name)

municipios/forms.py
from django import forms

from municipios.models import Municipio

class CreateMunicipio(forms.Form):
    name = forms.CharField(max_length=20)

class MunicipiosSearchForm(forms.Form):
    date_from = forms.DateField(label=("Fecha Desde"),widget=forms.DateInput(attrs={'type':'date'}))
    date_to = forms.DateField(label=("Fecha Hasta"),widget=forms.DateInput(attrs={'type':'date'}))    
    municipio = forms.ModelChoiceField(queryset=Municipio.objects.all())

class MunicipioOnlyForm(forms.Form):
    municipio = forms.ModelChoiceField(queryset=Municipio.objects.all())
        

municipios/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import CSV as myCSV
from .models import Dato, Municipio
from punto_referencia.models import Dato as DatoClima, Punto_Referencia
from .forms import MunicipioOnlyForm, MunicipiosSearchForm
from django.contrib.auth.decorators import login_required
import pandas as pd
from django.core.paginator import Paginator
import csv
import boto3
from django.conf import settings

""" 
Vista para los gráficos de Cultivos
"""
@login_required
def chartView(request):
    qs=qsTodos=municipio=date_from=date_to=id_municipio=nombreMunicipio=datos=datosTodos=years=municipiosTodos=None
    produccionPromedio=rendimientoPromedio=areaPromedio=añoMaximo=añoMinimo=None
    form = MunicipiosSearchForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():            
            date_from = request.POST.get('date_from')
            date_to = request.POST.get('date_to')
            id_municipio = request.POST.get('municipio')
            municipio = Municipio.objects.get(id=id_municipio)   
            nombreMunicipio=municipio.name
            #Conjunto de datos del municipio seleccionado
            qs = Dato.objects.filter(
                    municipio=municipio,
                    year__lte=date_to,
                    year__gte = date_from                
                    )  
            #Obtener el total de produccion anual
            df = pd.DataFrame(list(qs.values('year', 'produccion','rendimiento','area_sembrada')))
            produccionPromedio = df.produccion.mean() #Aun son datos por periodo
            rendimientoPromedio = df.rendimiento.mean()
            areaPromedio = df.area_sembrada.mean()
            dati=df.groupby(pd.PeriodIndex(df['year'], freq="Y"))['produccion'].sum().reset_index()                                    
            datos = [i for i in dati['produccion'].values]
            years = [i for i in dati['year'].values]    
            añoMinimo= min(years) 
            añoMaximo=max(years)
            #Obtener el total de produccion todos los municipios      
            qsTodos = Dato.objects.filter(year__lte=date_to,year__gte = date_from)            
            dfTodos = pd.DataFrame(list(qsTodos.values('year', 'produccion','municipio')))
            dfTodos.municipio = dfTodos.municipio.apply(lambda x: Municipio.objects.get(id=x).name)
            dfTodosAgrup = dfTodos.groupby('municipio')['produccion'].sum().reset_index()
            dfTodosAgrup = dfTodosAgrup.sort_values(by=['produccion'], ascending=False)
            datosTodos = [i for i in dfTodosAgrup['produccion'].values]            
            municipiosTodos = [i for i in dfTodosAgrup['municipio'].values]            

    context={
        'form':form,
        'qs':qs,
        'years':years,
        'datosProdAnual':datos,
        'municipio':nombreMunicipio,
        'datosTodos':datosTodos,
        'municipiosTodos':municipiosTodos,
        'añoMinimo':añoMinimo,
        'añoMaximo':añoMaximo,
        'produccionPromedio':produccionPromedio,
        'rendimientoPromedio':rendimientoPromedio,
        'areaPromedio':areaPromedio,
    }
    return render(request,'municipios/charts.html', context)

""" 
Vista para los gráficos de Agroclima (Clima vs Rendimiento)
"""
@login_required
def AgroClimateView(request):
    qsCultivo=qsClima=qs=df=Temp_Y=Hum_Y=Prec_Y=Rad_Y=municipio=None
    lista_Temp_Y = []
    lista_Prec_Y = []
    lista_Hum_Y = []
    lista_Rad_Y = []
    
    form = MunicipioOnlyForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid(): 
            municipio=form.cleaned_data.get('municipio')  
            qs = Punto_Referencia.objects.filter(municipio=municipio)
            if qs:
                qsCultivo = Dato.objects.filter(
                        municipio=municipio              
                        )   
                #Obtener el primer objeto punto referencia perteneciente al municipio
                punto_referencia =  Punto_Referencia.objects.filter(municipio=municipio)[:1].get()
                qsClima = DatoClima.objects.filter(
                    year__gte = '2006-07-01' ,
                    year__lte= '2018-06-30',##### ARREGLAR!!
                    punto_referencia = punto_referencia
                )
                #Lectura datos de cultivo y rendimiento para ese periodo de tiempo.
                df = pd.DataFrame(list(qsCultivo.values('year','period','rendimiento')))    
                df2 = pd.DataFrame(list(qsClima.values('year','irradiance','temperature','relative_humidity','precipitation')))    
                df2['year'] = pd.to_datetime(df2['year'])
                df2=df2.set_index('year')            
                years = df2.index.year.astype(int)
                semes = (df2.index.month.astype(int) - 1) // 6
                #Los datos de clima se agrupan por semestre
                df2_semestral = df2.groupby([years, semes])['irradiance','relative_humidity','temperature'].mean()
                df2_semestral['precipitation'] = df2.groupby([years, semes])['precipitation'].sum()
                df2_semestral.index.names=['year','period']
                df2_semestral=df2_semestral.reset_index()
                df2_semestral['period'] = df2_semestral.apply(lambda row: "".join([str(int(row['year'])),"A"]) if row['period'] == 0 else "".join([str(int(row['year'])),"B"]),axis=1)             
                #Agregar las columnas 'rendimiento' y 'period' del dataframe de los cultivos 
                #al dataframe con los datos del clima agrupados por semester (df2_semestral)
                df_merged = pd.merge(df[['rendimiento','period']],df2_semestral, on="period", how="left")
                df_merged['irradiance']=df_merged['irradiance'].apply(lambda x: round(x,2))            
                df_merged['relative_humidity']=df_merged['relative_humidity'].apply(lambda x: round(x,2))            
                df_merged['temperature']=df_merged['temperature'].apply(lambda x: round(x,2))            
                df_merged['precipitation']=df_merged['precipitation'].apply(lambda x: round(x,2))            
                df_merged['rendimiento']=df_merged['rendimiento'].apply(lambda x: round(x,2))  
                #Se crean diferentes listas para el conjunto x,y con los datos de la variable climática vs rendimiento
                for h, w in zip(df_merged['temperature'], df_merged['rendimiento']):
                    lista_Temp_Y.append({'x': h, 'y': w})
                for h, w in zip(df_merged['precipitation'], df_merged['rendimiento']):
                    lista_Prec_Y.append({'x': h, 'y': w})
                for h, w in zip(df_merged['relative_humidity'], df_merged['rendimiento']):
                    lista_Hum_Y.append({'x': h, 'y': w})
                for h, w in zip(df_merged['irradiance'], df_merged['rendimiento']):
                    lista_Rad_Y.append({'x': h, 'y': w})
                Temp_Y = str(lista_Temp_Y).replace('\'', '')
                Prec_Y = str(lista_Prec_Y).replace('\'', '')
                Hum_Y = str(lista_Hum_Y).replace('\'', '')
                Rad_Y = str(lista_Rad_Y).replace('\'', '')
            
    context = {
        'form':form,
        'qs':qs,
        'df':df,
        'Temp_Y':Temp_Y,
        'Prec_Y':Prec_Y,
        'Hum_Y':Hum_Y,
        'Rad_Y':Rad_Y,
        'municipio':municipio,
    }
    return render(request,'municipios/agroclimate.html', context)

""" 
Vista reportes de cultivos
"""
@login_required
def reports_view(request):
    form = MunicipiosSearchForm(request.POST or None)
    no_data = obj = datos=municipio=date_from=date_to=date_min=date_max=None
    objs = []

    if request.method == 'POST':
        if form.is_valid():
            date_from = request.POST.get('date_from')
            date_to = request.POST.get('date_to')
            id_municipio = request.POST.get('municipio')
            municipio = Municipio.objects.get(id=id_municipio)   
            objs = Dato.objects.filter(
                    municipio=municipio,
                    year__lte=date_to,
                    year__gte = date_from                
                    )  
            date_max=objs.last().year.strftime("%Y")
            date_min=objs.first().year.strftime("%Y")
            obj = objs[:5]    
            #Se usan cookies para guardar el municipio y el rango de tiempo para usarlos en la vista de exportar.
            request.session['municipio'] = id_municipio
            request.session['date_to'] = date_to
            request.session['date_from'] = date_from
            if len(obj) == 0:
                no_data = 'No se encontraron registros en las fechas seleccionadas.'
        #Mostrar los 5 primeros registros encontrados
        p = Paginator(obj,5)        
        page = request.GET.get('page')
        datos = p.get_page(page) 

    context={
        'form': form,
        'obj': obj,  
        'cantidad':len(objs),
        'date_from':date_min,
        'date_to':date_max,
        'municipio':municipio, 
        'datos': datos,
        'no_data': no_data,
    }
    return render(request,'municipios/reports.html', context)

""" 
Función para exportar los datos del cultivo consultados en la vista de reportes como CSV.
"""
def export(request):
    #Se obtienen el municipio y el rango de tiempo guardadas en la sesión
    id_municipio=request.session['municipio'] 
    municipio = Municipio.objects.get(id=id_municipio)                        
    date_to=request.session['date_to'] 
    date_from=request.session['date_from'] 
    obj = Dato.objects.filter(
                    municipio=municipio,
                    year__lte=date_to,
                    year__gte = date_from                
                    )  
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)

municipios/templates/municipios/agroclimate.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Gráficos Clima vs Cultivo{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'municipios/style.css' %}">
{% endblock styles %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>
<script>
function getRandomColor(a) {
    var r = Math.floor(Math.random() * 255);
    var g = Math.floor(Math.random() * 255);
    var b = Math.floor(Math.random() * 255);
    return "rgba(" + r + "," + g + "," + b + ", " + a + ")";
}

$(document).ready(function(){
    const ctx = document.getElementById('Temp_Y').getContext('2d');    
    const ctx2 = document.getElementById('Prec_Y').getContext('2d');    
    const ctx3 = document.getElementById('Hum_Y').getContext('2d');    
    const ctx4 = document.getElementById('Rad_Y').getContext('2d');    

    const Temp_Y = new Chart(ctx, {
        type: 'scatter',
        data: {
            datasets: [{
                label: 'Temperatura (°C) vs Rendimiento (Ton/Ha)',                
                data: {{Temp_Y}},
                backgroundColor:getRandomColor(1),
                borderColor:getRandomColor(1),
            }]
        },
        options: {                          
            scales: {
                y: {
                    beginAtZero: true,                        
                }
            },
        }
    });
    const Prec_Y = new Chart(ctx2, {
        type: 'scatter',
        data: {
            datasets: [{
                label: ' Precipitacion (mm) vs Rendimiento (Ton/Ha)',                
                data: {{Prec_Y}},
                backgroundColor:getRandomColor(1),
                borderColor:getRandomColor(1),
            }]
        },
        options: {                          
            scales: {
                y: {
                    beginAtZero: true,                        
                }
            },
        }
    });
    const Hum_Y = new Chart(ctx3, {
        type: 'scatter',
        data: {
            datasets: [{
                label: 'Humedad Relativa (%) vs Rendimiento (Ton/Ha)',                
                data: {{Hum_Y}},
                backgroundColor:getRandomColor(1),
                borderColor:getRandomColor(1),
            }]
        },
        options: {                          
            scales: {
                y: {
                    beginAtZero: true,                        
                }
            },
        }
    });
    const Rad_Y = new Chart(ctx4, {
        type: 'scatter',
        data: {
            datasets: [{
                label: 'Radiación (MJ/m^2) vs Rendimiento (Ton/Ha)',                
                data: {{Rad_Y}},
                backgroundColor:getRandomColor(1),
                borderColor:getRandomColor(1),
            }]
        },
        options: {                          
            scales: {
                y: {
                    beginAtZero: true,                        
                }
            },
        }
    });
});
</script>
<script>
    // Exportar a PDF
    $(document).ready(function(){
    $('#downloadPdf').click(function(event) {
        // get size of report page
        var reportPageHeight = $('#graphs').innerHeight();
        var reportPageWidth = $('#graphs').innerWidth();
      
        // create a new canvas object that we will populate with all other canvas objects
        var pdfCanvas = $('<canvas />').attr({
          id: "canvaspdf",
          width: reportPageWidth,
          height: reportPageHeight
        });
      
        // keep track canvas position
        var pdfctx = $(pdfCanvas)[0].getContext('2d');
        var pdfctxX = 0;
        var pdfctxY = 0;
        var buffer = 100;
      
        // for each chart.js chart
        $("canvas").each(function(index) {
          // get the chart height/width
          var canvasHeight = $(this).innerHeight();
          var canvasWidth = $(this).innerWidth();
      
          // draw the chart into the new canvas
          pdfctx.drawImage($(this)[0], pdfctxX, pdfctxY, canvasWidth, canvasHeight);
          pdfctxX += canvasWidth + buffer;
      
          // our report page is in a grid pattern so replicate that in the new canvas
          if (index % 2 === 1) {
            pdfctxX = 0;
            pdfctxY += canvasHeight + buffer;
          }
        });
      
        // create new pdf and add our new canvas as an image
        var pdf = new jsPDF('l', 'pt', [reportPageWidth, reportPageHeight]);
        
        pdf.setFont("helvetica");
        pdf.setFontType("bold");
        pdf.setFontSize(22);
        pdf.setTextColor(30,64,40);
        pdf.text(reportPageWidth/2-50,50,'{{municipio|title}}');


        pdf.addImage($(pdfCanvas)[0], 'PNG', 150, 100);
      
        // download the pdf
        pdf.save('graficos_cultivo.pdf');
      });
    });
</script>
    
{% endblock scripts %}

{% block content %}
<br/>
<h1 class="headers">Agroclima</h1>
<hr/>
<div class="bloque">    
<form action="" id="dataForm" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary mt-3">Consultar</button>
</form>
</div>
{% if qs %}

<h1 class="headers text-center">Clima vs Rendimiento</h1>
<h2 class="headers text-center">Semestral</h2>
<hr/>
<br/>

<div class="d-flex justify-content-center">
    <a href="#" class="btn btn-outline-secondary btn-lg my-4" id="downloadPdf">
        <i class="fa fa-download me-2" aria-hidden="true"></i>
    Exportar como PDF</a>
</div>

<!-- Charts -->
<div  id="graphs">
    <div class="graphs">                                    
        <div class="box"><canvas id="Temp_Y"></canvas></div>                  
        <div class="box"><canvas id="Hum_Y"></canvas></div>                  
        <div class="box"><canvas id="Prec_Y"></canvas></div>                  
        <div class="box"><canvas id="Rad_Y"></canvas></div>                  
    </div>
</div>

{% else %}
<div class="alert alert-info mt-3" role="alert">
    No hay datos para mostrar. Seleccione una opción.
</div>
{% endif %}
{% endblock content %}

municipios/templates/municipios/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'municipios/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}Maiz{% endblock title %}

{% block content %} 
<h1 class="headers">Módulo Maíz</h1>
<hr><br>
<br>
<div class="row align-items-center">
    <div class="col-6">
        <div id="alert-box2"></div>
        <form id="my-dropzone2" class="dropzone dz">
            {% csrf_token %}
            <div class="dz-message needsclick">
                <!--begin::Icon-->
                <i class="fa fa-cloud-upload fa-5x" aria-hidden="true"></i>
                <!--end::Icon-->
                <br>
                <br>
                <!--begin::Info-->
                <div class="ms-4">
                    <h3 class="headers">Arrastra o Selecciona el archivo de carga.</h3>
                    <span class="fs-7 fw-semibold text-gray-400">Máximo 1 archivo en CSV.</span>
                </div>
                <div class="fallback">
                    <input name="file" type="file" /> 
                </div>
                <!--end::Info-->
            </div>
        </form>
    </div>

    <div class="col-6 text-center">
        <h4>Este módulo se encarga de almacenar los datos correspondientes
            al maíz.
        </h4><br>
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Al momento de cargar un archivo tener en cuenta:</h4>
            <hr>
            <p>Cargar un único archivo a la vez.</p>          
            <p>Sólo se admiten archivos en formato .csv.</p>        
        </div>
    </div>

    
</div>

<button id="upload-btn" type="submit" class="btn btn-success m-3">Guardar</button>

{% endblock content %}

municipios/templates/municipios/reports.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% url 'municipios:export' as export %}


{% block title %}Reportes Cultivos{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'municipios/style.css' %}">
{% endblock styles %}
{% block content %}
<br/>
<h1 class="headers">Reportes Cultivo Maíz</h1>
<hr/>
<br/>
<div class="bloque">    
    <form action="" id="dataForm" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary mt-3">Consultar</button>
    </form>
</div>
    <br>        
    {% if obj %}
        <h3 class="headers">Boletín informativo del municipio {{municipio.name}} </h3>
            <h4 class="headers">Datos históricos entre {{date_from}} y {{date_to}}</h4>
        <hr/>
            <a href={% url 'municipios:export' %} class="btn btn-success mt-3 mb-3">Exportar como CSV</a>            
            <table class="text-center table table-hover table-striped table-bordered mt-3">
                <thead>
                <tr >
                    <th scope="col">Fecha</th>
                    <th scope="col">Periodo</th>
                    <th scope="col">Area Sembrada</th>
                    <th scope="col">Area Cosechada</th>
                    <th scope="col">Produccion</th>
                    <th scope="col">Rendimiento</th>
                    <th scope="col">Municipio</th>
                </tr>
                </thead>
                <tbody> 
                    {% for o in obj %}                
                        <tr>
                            <th scope="row">{{o.year}}</th>
                            <td class="table-warning">{{o.period}}</td>
                            <td class="table-success">{{o.area_sembrada}}</td>
                            <td class="table-primary">{{o.area_cosechada}}</td>
                            <td class="table-info">{{o.produccion}}</td>
                            <td class="table-light">{{o.rendimiento|floatformat:2}}</td>                            
                            <td class="table-light">{{o.municipio}}</td>                            
                        </tr>   
                    {% endfor %}            
                </tbody>
            </table>
            <p>5 primeros resultados de {{cantidad}}</p>
            <br/>
            <hr/>
    {% endif %}        
    {% if no_data %}
        <div class="alert alert-danger" role="alert">
            {{no_data}}
        </div>      
    {% endif %}

{% endblock content %}