ebdjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,news_view
from .forms import EmailValidationOnForgotPassword, MyAuthenticationForm, MySetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('noticias/', news_view, name='news'),    
    path('municipios/', include('municipios.urls', namespace='municipios')),
    path('punto_referencia/', include('punto_referencia.urls', namespace='punto_referencia')),
    path('perfiles/', include('perfiles.urls', namespace='perfiles')),    
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html',authentication_form=MyAuthenticationForm ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),        
    path('password-reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword,template_name="auth/password_reset.html"), name='password_reset'),            
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"), name='password_reset_done'),            
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auth/password_reset_confirm.html", form_class=MySetPasswordForm), name='password_reset_confirm'),            
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"), name='password_reset_complete'),            
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

municipios/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from .views import create_municipio_view,csv_upload_view,export,reports_view,chartView,AgroClimateView

app_name = 'municipios'

urlpatterns = [
 path('maiz/', create_municipio_view, name = "maiz"),   
 path('upload/', csv_upload_view, name='upload'),
 path('charts/', chartView, name='charts'),
 path('charts/agroclima/', AgroClimateView, name='agroclimate'),
 path('reports/', reports_view, name='reports'),
 path('export/', export, name='export'),

]

perfiles/urls.py
from django.urls import path
from .views import my_profile_view,create_user_view,delete_user_view,user_list_view,show_user_view,MyPasswordChangeView,MyPasswordChangeDoneView,descargar_manual_view
from .forms import MyChangePasswordForm

app_name = 'perfiles'

urlpatterns = [
    path('mi_perfil/', my_profile_view, name='mi-perfil'),
    path('create_user/', create_user_view, name='create-user'),
    path('list_users/', user_list_view, name='list-user'),
    path('delete_user/<user_id>/', delete_user_view, name='delete-user'),
    path('show_user/<user_id>/',  show_user_view, name='show-user'),
    path('change_password/', MyPasswordChangeView.as_view(form_class=MyChangePasswordForm), name='password-change'),
    path('change_password/done/', MyPasswordChangeDoneView.as_view(), name='password-change-done'),
    path('manual_usuario/', descargar_manual_view, name='ver-manual'),
]

punto_referencia/urls.py
from django.urls import path
from .views import (
    reports_view, 
    chartView,
    csv_upload_view,
    mapView,
    uploadTemplateView,
    load_punto_referencia,
    export
    )

app_name = 'punto_referencia'

urlpatterns = [
    path('reports/', reports_view, name='reports'),
    path('charts/', chartView, name='charts'),
    path('clima/', uploadTemplateView, name='clima'),
    path('upload/', csv_upload_view, name='upload'),
    path('map/', mapView, name='map'),
    path('export/', export, name='export'),
    path('ajax/load-cities/', load_punto_referencia, name='ajax_load_cities'),  # <-- this one here
   
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    
    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Font Awsome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- Dropzone js -->
    {% comment %} <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script> {% endcomment %}
    <script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js" defer></script>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block styles %}{% endblock styles %}
    <title>SIGAGRO | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block scripts %}
        {% endblock scripts %}

        {% block content %}
        {% endblock content %}
    </div>
    <footer class="footer container-fluid text-center ">
      <div class="row">
          <div class="col-sm-4">
              <h3>Contáctenos</h3>    
              <hr>
              <h4>Teléfono: 3112813845</h4>
              <h4>Bucaramanga - Colombia</h4>
              <h4>Cra. 27 # 9</h4>
              
          </div>
          <div class="col-sm-5">
              <h3>Redes Sociales</h3>
              <br>
              <a href="#" id="fa" class="fa fa-facebook"></a>
              <a href="#" id="fa" class="fa fa-twitter"></a>
              <a href="#" id="fa" class="fa fa-linkedin"></a>
              <a href="#" id="fa" class="fa fa-youtube"></a>
          </div>
          <div class="col-sm-3">
              <img src="{% static 'logo.png' %}" class="img-fluid" style="border-radius: 55%; height: 190px;">
          </div>
      </div>
  </footer>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/home.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Font Awsome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js" defer></script>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>SIGAGRO | Inicio</title>
  </head>

<body>
    {% include 'navbar.html' %}

<div id="home" style="background: url('{% static 'crops.jpg' %}') no-repeat center center fixed;">
    <div class="landing-text" >
            <h1>SIGAGRO</h1>
            <h3>Sistema de Información para la Gestión Agroclimática</h3>
    </div>
</div>

<div class="padding">
        <div class="row">
            <div class="col-sm-6">
                <img src="{% static 'climat.jpg' %}" class="img-fluid rounded">
            </div>
            <div class="col-sm-6 align-self-center text-center">
                <h2> Estudie el comportamiento del clima</h2>
                <p class="lead">Estudia la dinámica espaciotemporal del clima durante los últimos 40 años 
                    en un lugar específico.
                </p>
                <p class="lead">
                    Conozca y aproveche la variación de la oferta climática para optimizar el
                    rendimiento de los cultivos. Consulte la información histórica del clima, genera gráficos interactivos, consulta reportes históricos
                    y exportalos como CSV. 
                </p>                
            </div>
        </div>
</div>

<div class="padding">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-end"> 
                <h4>Gestione los datos</h4>
                <p>  El prototipo de sistema de información provee un módulo para análisis estadísicos 
                    mediante el uso de paneles de control (dashboard) interactivos.   </p>                
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12"> 
                <img src="{% static 'manage.jpg' %}" class="img-fluid">
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-end"> 
                <h4>Analice el comportamiento de las variables</h4>
                <p> Estudie el comportamiento del rendimiento histórico que ha
                    tenido la producción de los cultivos en su región.
                </p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12"> 
                <img src="{% static 'estadistica.jpg' %}" class="img-fluid rounded">
            </div>
        </div>
</div>

<div id="fixed" style="background: url('{% static 'crops4.jpg' %}') no-repeat center center fixed;"></div>

<div class="padding">    
        <div class="row text-center">
            <div class="col-sm-12 mb-4">                                
                <h4> Información sobre los datos </h4> 
                <p> Los datos que se presentan en este prototipo de sistema de información contienen la información relacionada al clima promedio
                    diario y de los cultivos de forma semestral y anual en los municipios y lugares geográficos definidos para el estudio en las zonas norte y sur del departamento de Cesar.
                </p>                    
            </div>
            <div class="col-sm-6">                                
                <p>Los datos históricos relacionados al clima son proporcionados mediante la observación satelital por parte del centro de investigación de Langley de la NASA a través 
                    de la división Earth Science de la agencia. 
                    Los conjuntos de datos para cada zona se obtuvieron del portal web 
                    cartográfico de fácil uso <a href="https://power.larc.nasa.gov/data-access-viewer/" class="link-primary" target="_blank">
                    NASA POWER Data Acess Viewer.</a>                    
                </p>
                <p>Para consultar más información ingrese <a href="https://power.larc.nasa.gov/docs/methodology/" class="link-primary" target="_blank">aquí.</a></p>
            </div>   
            <div class="col-sm-6">                
                <p>Los datos históricos de los cultivos son proporcionados por el Ministerio de Agricultura 
                    y Desarrollo Rural de Colombia, y fueron obtenidos de <a href="https://www.datos.gov.co/d/2pnw-mmge" class="link-primary" target="_blank">Evaluaciones Agropecuarias Municipales EVA </a>,
                    disponibles en <i>Datos Abiertos</i>.
                </p>
            </div>
        </div>
</div>

<footer class="container-fluid text-center">
    <div class="row">
        <div class="col-sm-4">
            <h3>Contáctenos</h3>    
            <hr>
            <h4>Teléfono: +573112813845</h4>
            <h4>Correo: sigagros@gmail.com</h4>
            <h4>Bucaramanga - Colombia</h4>
            <h4>Cra. 27 # 9</h4>
            
        </div>
        <div class="col-sm-5">
            <h3>Redes Sociales</h3>
            <br>
            <a href="#" id="fa" class="fa fa-facebook"></a>
            <a href="#" id="fa" class="fa fa-twitter"></a>
            <a href="#" id="fa" class="fa fa-instagram"></a>
            <a href="#" id="fa" class="fa fa-linkedin"></a>
            <a href="#" id="fa" class="fa fa-youtube"></a>
        </div>
        <div class="col-sm-3">
            <img src="{% static 'logo.png' %}" class="img-fluid" style="border-radius: 55%; height: 190px;">
        </div>
    </div>
</footer>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</html>

templates/navbar.html
{% load static %}

{% url 'home' as path_to_home %}
{% url 'news' as path_to_news %}
{% url 'reports' as path_to_reports %}
{% url 'perfiles:mi-perfil' as path_to_my_profile %}
{% url 'perfiles:list-user' as path_to_manage_users %}
{% url 'perfiles:ver-manual' as path_to_manual %}
{% url 'municipios:charts' as path_to_municipios_charts %}
{% url 'municipios:agroclimate' as path_to_agroclimate %}
{% url 'municipios:maiz' as path_to_municipios %}
{% url 'municipios:reports' as path_to_municipios_reports %}
{% url 'punto_referencia:reports' as path_to_punto_referencia_reports %}
{% url 'punto_referencia:clima' as path_to_upload %}
{% url 'punto_referencia:charts' as path_to_punto_referencia_charts %}
{% url 'punto_referencia:map' as path_to_map %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(6, 43, 17, 0.9);">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path_to_home}}"><img src="{% static 'logo.png' %}" class="logo-sm"></a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">        
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href="{{path_to_home}}">Inicio</a>
        </li>             
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_map %}active{% endif %}" href="{{path_to_map}}">Mapa</a>
        </li>     
        {% if request.user.is_authenticated %}
          {% if request.user.is_staff %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              Cargar Datos
            </a>
            <div class="dropdown-menu">                        
              <a class="dropdown-item" href="{{path_to_upload}}">Cargar Datos Clima</a>
              <a class="dropdown-item" href="{{path_to_municipios}}">Cargar Datos Cultivo</a>            
            </div>
          </li> 
          {% endif %}        
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Graficos
              </a>
              <div class="dropdown-menu">                        
                <a class="dropdown-item" href="{{path_to_punto_referencia_charts}}">Clima</a>
                <a class="dropdown-item" href="{{path_to_municipios_charts}}">Cultivo</a>            
                <a class="dropdown-item" href="{{path_to_agroclimate}}">Agroclima</a>            
              </div>
            </li> 
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Reportes
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{{path_to_punto_referencia_reports}}">Clima</a>            
                <a class="dropdown-item" href="{{path_to_municipios_reports}}">Cultivo</a>            
              </div>
            </li>            
          {% endif %}           
          <li class="nav-item">
            <a class="nav-link {% if request.path == path_to_news %}active{% endif %}" href="{{path_to_news}}">Noticias</a>
          </li>   
          {% if request.user.is_staff %}       
            <li class="nav-item">
              <a class="nav-link {% if request.path == path_to_manage_users  %}active{% endif %}" href="{{path_to_manage_users }}">Gestión de Usuarios</a>
            </li>  
          {% endif %}           
       
      </ul>
    </div>

    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="{{request.user.perfil.foto.url}}" class="avatar-sm">  &nbsp;  
          <span style="color:wheat;">{{request.user}}</span>
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item {% if request.path == path_to_my_profile %} active{% endif %}" href="{{path_to_my_profile}}">Mi Perfil</a></li>
          <li><a class="dropdown-item {% if request.path == path_to_manual %} active{% endif %}" href="{{path_to_manual}} "target="_blank">Manual de Usuario</a></li>
          <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a></li>          
        </ul> 
      </div>
    {% else %}
      <a class="nav-link" href="{% url 'login' %}" style="color:darkseagreen;" >Iniciar Sesión</a>
    {% endif %}
    
  </div>
</nav>